# Generated by Django 5.2.15 on 2026-08-20 07:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterEmergent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mots_cles', models.CharField(help_text='Mots/expressions dominants du cluster (séparés par des virgules)', max_length=500)),
                ('nb_signalements', models.PositiveIntegerField(default=0)),
                ('silhouette_score', models.FloatField(blank=True, help_text='Score de cohérence interne du clustering (plus proche de 1 = mieux)', null=True)),
                ('nom_valide', models.CharField(blank=True, help_text='Nom donné par un modérateur si ce cluster est confirmé comme nouvelle catégorie', max_length=100, null=True)),
                ('statut', models.CharField(choices=[('a_examiner', 'À examiner'), ('confirme', 'Confirmé comme nouvelle catégorie'), ('rejete', 'Rejeté (bruit / faux positif)')], default='a_examiner', max_length=15)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id_signalement', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('profil_vendeur', models.CharField(blank=True, max_length=100, null=True)),
                ('type_arnaque', models.CharField(blank=True, choices=[('faux_vendeur', 'Faux vendeur'), ('phishing', 'Hameconnage (phishing)'), ('usurpation_identite', "Usurpation d'identite"), ('produit_non_livre', 'Produit non livre'), ('autre', "Autre type d'arnaque")], max_length=30, null=True)),
                ('description', models.TextField(verbose_name='Description du signalement')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuve'), ('rejete', 'Rejete'), ('transmis', "Transmis a l'autorite"), ('confirme', "Confirme par l'autorite"), ('infirme', "Infirme par l'autorite")], default='en_attente', max_length=15)),
                ('score', models.PositiveSmallIntegerField(default=100, help_text='Score de confiance communautaire (0 à 100)', validators=[django.core.validators.MaxValueValidator(100)])),
                ('categorie_predite', models.CharField(blank=True, help_text='Catégorie devinée automatiquement par le modèle de classification', max_length=50, null=True)),
                ('confiance', models.FloatField(blank=True, help_text='Confiance du modèle (0 à 1)', null=True)),
                ('categorie_corrigee', models.CharField(blank=True, help_text='Renseigné par un modérateur si la prédiction IA était fausse', max_length=50, null=True)),
                ('score_risque', models.FloatField(blank=True, help_text='Score de risque calculé par le modèle IA', null=True)),
                ('canal_detecte', models.CharField(blank=True, max_length=30)),
                ('campagne_detectee', models.BooleanField(default=False)),
                ('signalements_lies', models.PositiveIntegerField(default=0, help_text="Nombre d'autres signalements partageant le même numéro/lien")),
                ('cluster_emergent', models.ForeignKey(blank=True, help_text="Renseigné automatiquement si ce signalement 'Incertain' a été rattaché à un cluster émergent", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='signalements.clusteremergent')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Signalement',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='Preuve',
            fields=[
                ('id_preuve', models.AutoField(primary_key=True, serialize=False)),
                ('fichier_url', models.CharField(max_length=300)),
                ('type_fichier', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document')], max_length=10)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('id_signalement', models.ForeignKey(db_column='id_signalement', on_delete=django.db.models.deletion.CASCADE, related_name='preuves', to='signalements.signalement')),
            ],
            options={
                'db_table': 'Preuve',
                'ordering': ['date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_examen', "En cours d'examen"), ('transmis_police', 'Transmis à la police / justice'), ('classe_sans_suite', 'Classé sans suite'), ('resolu', 'Résolu')], default='recu', max_length=20)),
                ('veracite', models.CharField(choices=[('non_examine', 'Non examinée'), ('confirme', "Confirmée : c'est une arnaque"), ('infirme', 'Infirmée : signalement non fondé')], default='non_examine', max_length=15)),
                ('commentaire_autorite', models.TextField(blank=True, help_text="Notes de l'autorité compétente sur ce dossier")),
                ('date_transmission', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('signalement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='signalements.signalement')),
            ],
            options={
                'ordering': ['-date_transmission'],
            },
        ),
        migrations.CreateModel(
            name='EntiteSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entite', models.CharField(choices=[('telephone', 'Téléphone'), ('lien', 'Lien')], max_length=15)),
                ('valeur', models.CharField(db_index=True, max_length=255)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entites', to='signalements.signalement')),
            ],
            options={
                'indexes': [models.Index(fields=['type_entite', 'valeur'], name='signalement_type_en_2a258d_idx')],
            },
        ),
    ]
