# Generated by Django 5.2.15 on 2026-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preuve',
            fields=[
                ('id_preuve', models.AutoField(primary_key=True, serialize=False)),
                ('fichier_url', models.CharField(max_length=300)),
                ('type_fichier', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document')], max_length=10)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Preuve',
                'ordering': ['date_upload'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id_signalement', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('profil_vendeur', models.CharField(blank=True, max_length=100, null=True)),
                ('type_arnaque', models.CharField(choices=[('faux_vendeur', 'Faux vendeur'), ('phishing', 'Hameçonnage (phishing)'), ('usurpation_identite', "Usurpation d'identité"), ('produit_non_livre', 'Produit non livré'), ('autre', "Autre type d'arnaque")], max_length=30)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('score', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'db_table': 'Signalement',
                'ordering': ['-date_signalement'],
                'managed': False,
            },
        ),
    ]
