# Generated by Django 6.0.7 on 2026-07-17 02:39

import django.db.models.deletion
# Generated by Django 5.2.15 on 2026-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Texte du signalement')),
                ('categorie_predite', models.CharField(max_length=50)),
                ('confiance', models.FloatField(help_text='Confiance du modèle (0 à 1)')),
                ('categorie_corrigee', models.CharField(blank=True, help_text='Renseigné par un modérateur si la prédiction était fausse', max_length=50, null=True)),
                ('score_risque', models.FloatField()),
                ('canal_detecte', models.CharField(blank=True, max_length=30)),
                ('campagne_detectee', models.BooleanField(default=False)),
                ('signalements_lies', models.PositiveIntegerField(default=0, help_text="Nombre d'autres signalements partageant le même numéro/lien")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EntiteSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entite', models.CharField(choices=[('telephone', 'Téléphone'), ('lien', 'Lien')], max_length=15)),
                ('valeur', models.CharField(db_index=True, max_length=255)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entites', to='signalements.signalement')),
            ],
            options={
                'indexes': [models.Index(fields=['type_entite', 'valeur'], name='signalement_type_en_2a258d_idx')],
            name='Preuve',
            fields=[
                ('id_preuve', models.AutoField(primary_key=True, serialize=False)),
                ('fichier_url', models.CharField(max_length=300)),
                ('type_fichier', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document')], max_length=10)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Preuve',
                'ordering': ['date_upload'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id_signalement', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('profil_vendeur', models.CharField(blank=True, max_length=100, null=True)),
                ('type_arnaque', models.CharField(choices=[('faux_vendeur', 'Faux vendeur'), ('phishing', 'Hameçonnage (phishing)'), ('usurpation_identite', "Usurpation d'identité"), ('produit_non_livre', 'Produit non livré'), ('autre', "Autre type d'arnaque")], max_length=30)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('score', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'db_table': 'Signalement',
                'ordering': ['-date_signalement'],
                'managed': False,
            },
        ),
    ]
