# Generated by Django 5.2.15 on 2026-08-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
