# Generated by Django 5.2.15 on 2026-07-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterEmergent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mots_cles', models.CharField(max_length=500)),
                ('nb_signalements', models.PositiveIntegerField(default=0)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('nom_valide', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('a_examiner', 'À examiner'), ('confirme', 'Confirmé comme nouvelle catégorie'), ('rejete', 'Rejeté (bruit / faux positif)')], default='a_examiner', max_length=15)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_examen', "En cours d'examen"), ('transmis_police', 'Transmis à la police / justice'), ('classe_sans_suite', 'Classé sans suite'), ('resolu', 'Résolu')], default='recu', max_length=20)),
                ('veracite', models.CharField(choices=[('non_examine', 'Non examinée'), ('confirme', "Confirmée : c'est une arnaque"), ('infirme', 'Infirmée : signalement non fondé')], default='non_examine', max_length=15)),
                ('commentaire_autorite', models.TextField(blank=True)),
                ('date_transmission', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('signalement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='signalements.signalement')),
            ],
            options={
                'ordering': ['-date_transmission'],
            },
        ),
        migrations.CreateModel(
            name='EntiteSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entite', models.CharField(choices=[('telephone', 'Téléphone'), ('lien', 'Lien')], max_length=15)),
                ('valeur', models.CharField(db_index=True, max_length=255)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entites', to='signalements.signalement')),
            ],
            options={
                'indexes': [models.Index(fields=['type_entite', 'valeur'], name='signalement_type_en_2a258d_idx')],
            },
        ),
    ]
