# Generated by Django 6.0.7 on 2026-07-17 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterEmergent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mots_cles', models.CharField(help_text='Mots/expressions dominants du cluster (séparés par des virgules)', max_length=500)),
                ('nb_signalements', models.PositiveIntegerField(default=0)),
                ('silhouette_score', models.FloatField(blank=True, help_text='Score de cohérence interne du clustering (plus proche de 1 = mieux)', null=True)),
                ('nom_valide', models.CharField(blank=True, help_text='Nom donné par un modérateur si ce cluster est confirmé comme nouvelle catégorie', max_length=100, null=True)),
                ('statut', models.CharField(choices=[('a_examiner', 'À examiner'), ('confirme', 'Confirmé comme nouvelle catégorie'), ('rejete', 'Rejeté (bruit / faux positif)')], default='a_examiner', max_length=15)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.AddField(
            model_name='signalement',
            name='cluster_emergent',
            field=models.ForeignKey(blank=True, help_text="Renseigné automatiquement si ce signalement 'Incertain' a été rattaché à un cluster émergent", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='signalements.clusteremergent'),
        ),
    ]
