# Generated by Django 6.0.7 on 2026-07-24 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalements', '0002_clusteremergent_signalement_cluster_emergent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_examen', "En cours d'examen"), ('transmis_police', 'Transmis à la police / justice'), ('classe_sans_suite', 'Classé sans suite'), ('resolu', 'Résolu')], default='recu', max_length=20)),
                ('veracite', models.CharField(choices=[('non_examine', 'Non examinée'), ('confirme', "Confirmée : c'est une arnaque"), ('infirme', 'Infirmée : signalement non fondé')], default='non_examine', max_length=15)),
                ('commentaire_autorite', models.TextField(blank=True, help_text="Notes de l'autorité compétente sur ce dossier")),
                ('date_transmission', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('signalement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='signalements.signalement')),
            ],
            options={
                'ordering': ['-date_transmission'],
            },
        ),
    ]
