# Generated by Django 5.2.15 on 2026-08-22 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signalements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id_vote', models.AutoField(primary_key=True, serialize=False)),
                ('type_vote', models.CharField(choices=[('up', 'Utile (+1)'), ('down', 'Pas utile (-1)')], max_length=4)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('id_signalement', models.ForeignKey(db_column='id_signalement', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='signalements.signalement')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Vote',
                'ordering': ['-date_vote'],
                'managed': True,
                'unique_together': {('id_signalement', 'id_utilisateur')},
            },
        ),
    ]
