# Generated by Django 5.2.15 on 2026-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id_vote', models.AutoField(primary_key=True, serialize=False)),
                ('type_vote', models.CharField(choices=[('up', 'Utile (+1)'), ('down', 'Pas utile (-1)')], max_length=4)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Vote',
                'ordering': ['-date_vote'],
                'managed': False,
            },
        ),
    ]
