# Generated by Django 5.2.15 on 2026-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id_audit', models.AutoField(primary_key=True, serialize=False)),
                ('table_cible', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=10)),
                ('id_utilisateur', models.IntegerField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'JournalAudit',
                'ordering': ['-date_action'],
                'managed': False,
            },
        ),
    ]
