# Generated by Django 5.2.15 on 2026-06-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(max_length=500)),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('est_masque', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Commentaire',
                'ordering': ['-date_commentaire'],
                'managed': False,
            },
        ),
    ]
