# Generated by Django 5.2.15 on 2026-08-20 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signalements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(max_length=500)),
                ('date_commentaire', models.DateTimeField(auto_now_add=True)),
                ('est_masque', models.BooleanField(default=False)),
                ('id_signalement', models.ForeignKey(db_column='id_signalement', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='signalements.signalement')),
                ('id_utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Commentaire',
                'ordering': ['-date_commentaire'],
                'managed': True,
            },
        ),
    ]
