# Generated by Django 5.2.15 on 2026-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.BinaryField(db_column='mot_de_passe_hash', max_length=256)),
                ('last_login', models.DateTimeField(blank=True, db_column='derniere_connexion', null=True)),
                ('sel', models.CharField(default='', max_length=36)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur'), ('autorite', 'Autorite competente')], default='user', max_length=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Utilisateur',
                'managed': True,
            },
        ),
    ]
